### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by JoeRadman** [kjwamlex/UWPortalRedesign#1]
Hi. The project doesn't compile. Do you want to have a quick look? Might be a simple fix. Thanks.

**Comment by kjwamlex** [comment]
Hello. 

This was originally built with Xcode 10 Beta last year. I'll make sure I update this project for Xcode 11 Beta so that it is ready for iOS and iPadOS 13 (and possibly for macOS using Catalyst) this year. 

Thanks for letting me know about the issue.

**Comment by kjwamlex** [comment]
This issue was related to Siri Intent. This is now resolved and working on iOS 13. 
I will also include demo video for this just in case you still can't build this. 

Siri Shortcuts are available by setting shortcuts inside Settings-Siri on iOS 12, and it is available in Shortcuts app on iOS 13 and iPadOS 13.

Thank you for checking out. (My code is still dirty :( )
